### ISSUE TITLE
Lade-Animation nach Speichern bleibt sichtbar

### ISSUE THREAD

**Issue by polarpixel** [dtpop/structure_plus#1]
Beim Speichern der Einstellungen bleibt die Lade-Animation sichtbar, aber die vorgenommenen Einstellungen werden dennoch gespeichert.

**Comment by dtpop** [comment]
Sorry - das ist kein Bug, das ist ein Feature.
Für die Farbfelder kann das AddOn uitools mit installiertem minicolors Plugin verwendet werden. Wenn das AddOn installiert ist, funktioniert auch das speichern.

**Comment by dtpop** [comment]
gefixt. Verwendung von minicolors ist optional (kein Pflichtaddon). Hinweis in Readme ergänzt.
