### ISSUE TITLE
Checkbox "Kategorien ausschließen"

### ISSUE THREAD

**Issue by polarpixel** [dtpop/structure_plus#2]
Da man im Normalfall alle Artikel anpassen will, würde ich die Checkbox standardmäßig aktivieren.

Und noch ein Vorschlag zum Text bei der Checkbox "Kategorien ausschließen" (ich musste ihn ziemlich lange lesen, um ihn zu kapieren):

---

Bei aktivierter Checkbox werden alle Kategorien angepasst mit Ausnahme der ausgewählten Kategorien im nächsten Feld. D.h. um die Anzeige sämtlicher Artikel anzupassen, bitte die Checkbox aktivieren und keine Kategorien auswählen.

Bei nicht aktivierter Checkbox werden lediglich die unten ausgewählten Kategorien angepasst.

**Comment by dtpop** [comment]
Text ist angepasst.
